config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/main/:filter' => 'pages#main', as: :main
  get '/main/:filter/tech' => 'pages#main', as: :tech_angular
  get '/main/:filter/info' => 'pages#main', as: :info_angular
  get '/main/:filter/calc' => 'pages#main', as: :calc_angular
  get '/main/:filter/sign' => 'pages#main', as: :sign_angular

  get '/tech/:filter' => 'pages#tech', as: :tech
  get '/info/:filter' => 'pages#info', as: :info

  get '/api/main/:filter' => 'api#main', as: :api_main
  get '/api/tech/:filter' => 'api#tech', as: :api_tech
  post '/api/feedback' => 'api#feedback', as: :api_feedback
  get '/api/expinfo' => 'api#all_exp', as: :api_all_exp
  get '/api/alltanks' => 'api#all_tanks', as: :api_all_tanks
  post '/api/wn8tank' => 'api#wn8_tank', as: :api_wn8_tank

  get '/api/sign' => 'api#sign_preview', as: :api_sign_preview
  get '/api/sign_save' => 'api#sign_save', as: :api_sign_save
  get '/api/sign/:id' => 'api#sign_show', as: :api_sign_show

  match '*path' => 'pages#index', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <meta name="format-detection" content="telephone=no">
  <meta charset="UTF-8">
  <!--<base href="/">-->
  <meta http-equiv="Content-Language" content="ru">
  <meta name='yandex-verification' content='582381a1c4dc9c16' />
  <meta name="google-site-verification" content="VeXbj5ODd8IKL3v0UtzUJWa6C-mZJvmW-sjeytJNlbs" />
  <meta name="description" content="Статистика World of Tanks">
  <meta name="keywords" content="WOT, World of tanks, Стата WOT, Статистика WOT, Статистика игрока World of Tanks, Статистика , Статистика World of Tanks, Игрока, World, Tanks, Имба WOT, Имба World of tanks, Имба, Нагибатор WOT, нагибатор World of tanks, Нагибатор, Рак WOT, Рак World of tanks, Рак , Раки, Реплей WOT, Реплей World of tanks, Танки статистика, Танки, Статистика мир танков, Статистика игрока мир танков, мир, Танков, Стата мир танков, Рейтинг Эффективности , WN7, WN8, нубометер , стволомерка, боевая эффективность World of tanks, wn8 что это, боевая Эффективность WOT, боевая эффективность мир танков, noobometer, xvm, рейтинг нагиба мир танков, рейтинг нагиба, рейтинг, нагиба, нагиб, моды WOT, моды мира танков, wotreplays, стата в вот, как проверить кпд, КПД ВОт, расширенная статистика в world of tanks, imbalol, imba, lol, imba lol, имбалол, имба лол">
  <link href="/favicon.ico" type="image/x-icon" rel="shortcut icon" />
  <title>Танки! Статистика. Имбалол сервис статистики World of tanks. Узнай свой wn8 кпд своих танков WOT!</title>

  <!-- CSS -->
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/animate.min.css" rel="stylesheet">
  <link href="/css/font-awesome.min.css" rel="stylesheet">
  <link href="/css/form.css" rel="stylesheet">
  <link href="/css/calendar.css" rel="stylesheet">
  <link href="/css/style.css" rel="stylesheet">
  <link href="/css/icons.css" rel="stylesheet">
  <link href="/css/generics.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="skin-blur-greenish">

    <%= content_for?(:application) ? yield(:application) : yield %>


    <!-- Javascript Libraries -->
    <script src="/js/jquery.min.js"></script> <!-- jQuery Library -->
    <script src="/js/jquery-ui.min.js"></script> <!-- jQuery UI -->
    <script src="/js/jquery.easing.1.3.js"></script> <!-- jQuery Easing - Requirred for Lightbox + Pie Charts-->

    <!-- Bootstrap -->
    <script src="/js/bootstrap.min.js"></script>

    <!-- Charts -->
    <script src="/js/charts/jquery.flot.js"></script> <!-- Flot Main -->
    <script src="/js/charts/jquery.flot.time.js"></script> <!-- Flot sub -->
    <script src="/js/charts/jquery.flot.animator.min.js"></script> <!-- Flot sub -->
    <script src="/js/charts/jquery.flot.resize.min.js"></script> <!-- Flot sub - for repaint when resizing the screen -->
    <script src="/js/charts/jquery.flot.pie.min.js"></script> <!-- Flot Pie chart -->
    <script src="/js/sparkline.min.js"></script> <!-- Sparkline - Tiny charts -->
    <!--<script src="js/easypiechart.js"></script> --> <!-- EasyPieChart - Animated Pie Charts -->
    <script src="/js/charts.js"></script> <!-- All the above chart related functions -->

    <!-- Map -->
    <script src="/js/maps/jvectormap.min.js"></script> <!-- jVectorMap main library -->
    <script src="/js/maps/usa.js"></script> <!-- USA Map for jVectorMap -->

    <!--  Form Related -->
    <script src="/js/icheck.js"></script> <!-- Custom Checkbox + Radio -->
    <script src="/js/select.min.js"></script>
    <script src="/js/colorpicker.min.js"></script>

    <!-- UX -->
    <script src="/js/scroll.min.js"></script> <!-- Custom Scrollbar -->
    <script src="/js/toggler.min.js"></script>
    <!-- Other -->
    <script src="/js/calendar.min.js"></script> <!-- Calendar -->
    <script src="/js/feeds.min.js"></script> <!-- News Feeds -->


    <!-- All JS functions -->
    <script src="/js/functions.js"></script>
    <!-- angular -->
    <!-- <script src="js/angular.min.js"></script> -->
    <script src="/js/angular.min.js"></script>
    <script src="/js/angular-route.min.js"></script>
    <!--<script src="js/angular-resource.min.js"></script> -->
    <!-- <script src="js/angular-route.min.js"></script> -->
    <!--<script src="js/angular-sanitize.min.js"></script> -->
    <script src="/js/angular/app.js"></script>
    <script src="/js/angular/services/search.service.js"></script>
    <script src="/js/angular/controllers/search.controller.js"></script>
    <script src="/js/angular/controllers/userdata.controller.js"></script>
    <script src="/js/angular/controllers/usertech.controller.js"></script>
    <script src="/js/angular/controllers/info.controller.js"></script>
    <script src="/js/angular/controllers/calc.controller.js"></script>
    <script src="/js/angular/controllers/sign.controller.js"></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-65571236-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter31780306 = new Ya.Metrika({
                        id:31780306,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/31780306" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    <!-- begin of Top100 code -->

<!--    <script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?3127360"></script>
    <noscript>
      <a href="http://top100.rambler.ru/navi/3127360/">
        <img src="http://counter.rambler.ru/top100.cnt?3127360" alt="Rambler's Top100" border="0" />
      </a>

    </noscript>-->
    <!-- end of Top100 code -->
    <!--LiveInternet counter-->
<!--    <script type="text/javascript">&lt;!&ndash;
    document.write("<a href='//www.liveinternet.ru/click' "+
            "target=_blank><img src='//counter.yadro.ru/hit?t25.12;r"+
            escape(document.referrer)+((typeof(screen)=="undefined")?"":
            ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
                    screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
            ";"+Math.random()+
            "' alt='' title='LiveInternet: показано число посетителей за"+
            " сегодня' "+
            "border='0' width='88' height='15'><\/a>")
    //&ndash;&gt;</script>&lt;!&ndash;/LiveInternet&ndash;&gt;-->
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/user_frame.html.erb
<%= content_for :application do %>

    <section ng-app="mainApp">
    <header id="header" class="media">
      <a href="" id="menu-toggle"></a>
      <span class="logo pull-left" ><%= @user.user_name unless @user.nil? %></span>
      <div class="media-body">
        <div class="media" id="top-menu">
          <div class="pull-left tm-icon">
            <a data-drawer="messages" class="drawer-toggle" href="">
              <i class="sa-top-message"></i>
              <span>Отправить отзыв</span>
            </a>
          </div>
          <div class="pull-left tm-icon">
            <a data-drawer="notifications" class="drawer-toggle" href="">
              <i class="sa-top-updates"></i>
              <span>О нас</span>
            </a>
          </div>
          <!-- <a href ng-click="toStart()"><span class="icon">&#61771;</span></a> -->
          <div id="time" class="pull-right">
            <span id="hours"></span>
            :
            <span id="min"></span>
            :
            <span id="sec"></span>
          </div>

          <!--<div class="media-body">
              <input type="text" class="main-search">
          </div> -->
        </div>
      </div>
    </header>

    <div class="clearfix"></div>

    <section id="main" class="p-relative" role="main" >

      <!-- Sidebar -->
      <aside id="sidebar">

        <!-- Sidbar Widgets -->
        <div class="side-widgets overflow">
          <!-- Profile Menu -->
          <div class="text-center s-widget m-b-25 dropdown" id="profile-menu">
            <a href="" data-toggle="dropdown">
              <img class="profile-pic animated" src="<%= @user.clan_emblem  unless @user.nil? %>" alt="<%= @user.clan_name  unless @user.nil? %>">
            </a>
            <h4 class="m-0"><%= @user.user_name  unless @user.nil? %></h4>
            <%= @user.clan_name  unless @user.nil? %>
          </div>

          <!-- Calendar -->
          <div class="s-widget m-b-25">
            <div id="sidebar-calendar"></div>
          </div>

          <!-- Feeds -->
          <div class="s-widget m-b-25">
            <h2 class="tile-title">
              Новости
            </h2>

            <div class="s-widget-body">
              <div id="news-feed"></div>
            </div>
          </div>

        </div>

        <!-- Side Menu -->
        <ul class="list-unstyled side-menu" ng-controller="MenuController">
          <li ng-class="{ active: isActive('/main/<%= params[:filter] %>')}">
            <%= link_to main_path(params[:filter]), class: "sa-side-home" do %>
            <!--<a class="sa-side-home" href>-->
              <span class="menu-item">Общая статистика</span>
            <% end  %>
            <!--</a>-->
          </li>
          <!--'active' if current_page?(:controller => 'pages', :action => 'tech')-->
          <li ng-class="{ active: isActive('/main/<%= params[:filter] %>/tech')}">
            <a class="sa-side-typography" href="/main/<%= params[:filter] %>/tech">
              <span class="menu-item">Список техники</span>
            </a>
          </li>
          <li ng-class="{ active: isActive('/main/<%= params[:filter] %>/info')}">
            <a class="sa-side-spam" href="/main/<%= params[:filter] %>/info">
              <span class="menu-item">Способы подсчета</span>
            </a>

          </li>
          <li ng-class="{ active: isActive('/main/<%= params[:filter] %>/calc')}">
            <a class="sa-side-widget" href="/main/<%= params[:filter] %>/calc">
              <span class="menu-item">Калькулятор WN8</span>
            </a>
          </li>
          <li ng-class="{ active: isActive('/main/<%= params[:filter] %>/sign')}">
            <a class="sa-side-photos" href="/main/<%= params[:filter] %>/sign">
              <span class="menu-item">Генератор подписи</span>
            </a>
          </li>          
          <li>
            <a class="sa-side-back" target="_self" data-ng-href="/" href="/">
              <span class="menu-item">Новый поиск</span>
            </a>
          </li>
        </ul>
      </aside>

      <!-- Content -->
      <section id="content" class="container">

        <div id="messages" class="tile drawer animated">
          <div class="listview narrow">
            <div class="media">
              <a href="">Отправить отзыв</a>
              <span class="drawer-close">&times;</span>

            </div>
            <div class="overflow" style="height: 254px" ng-controller="FeedbackController">
              <div class="media">
                <span>{{feedback.formInfo}}</span>
                <span class="error" ng-show="fedbackForm.femail.$error.email">Email не соответствует формату!</span>
                <form class="box tile animated active" id="box-login" ng-submit="sendFeedback()" name="fedbackForm">
                  <textarea class="form-control overflow" rows="8" ng-model="feedback.message" placeholder="Ваши предложения и пожелания..." required></textarea>
                  <input type="email" name="femail" class="form-control" placeholder="Ваш e-mail" ng-model="feedback.email" required >
                  <button class="btn btn-sm" type="submit" ng-disabled="!fedbackForm.$valid">Отправить</button>
                </form>
              </div>
            </div>
          </div>
        </div>

        <!-- Notification Drawer -->
        <div id="notifications" class="tile drawer animated">
          <div class="listview narrow">
            <div class="media">
              <a href >О нас</a>
              <span class="drawer-close">&times;</span>
            </div>
            <div class="overflow" style="height: 254px">
              <article class="block-area">
                <h3>imbalol.com</h3>
                <blockquote>
                  <p>Сервис получения краткой и полезной общей статистики для игрока World of tanks, в том числе wn8 кпд, wn7, % побед.
                    А также информации по технике игрока, детализация коэффициента wn8 по каждому танку.
                    Если вы заметили, что статистика считается неверно - сообщите нам примеры с конкретными игроками.
                  </p>
                </blockquote>
              </article>
            </div>
          </div>
        </div>
        <!-- Breadcrumb -->
        <ol class="breadcrumb hidden-xs">
          <li><a href="/main/<%= params[:filter] %>/info">Способы подсчета</a></li>
          <li><a target="_self" data-ng-href="/" href="/">Поиск</a></li>
          <!--<li><a href="#">Library</a></li> -->
          <li ng-class="{ active: isActive('/main/<%= params[:filter] %>')}">
<!--            <div ng-switch on="isActive('/main/<%= params[:filter] %>')">-->
                <a href="/main/<%= params[:filter] %>">Игрок</a>
<!--            </div>-->
          </li>
        </ol>

        <%= content_for?(:content) ? yield(:content) : yield %>
        <!-- params[:filter] -->
      </section>

    </section>
<!--    <script type="text/javascript">
      $(document).ready(function(){
          $('body').on('click touchstart', '#menu-toggle', function(e){
              e.preventDefault();
              $('html').toggleClass('menu-active');
              $('#sidebar').toggleClass('toggled');
              //$('#content').toggleClass('m-0');
          });

          $('body').on('click touchstart', '.drawer-toggle', function(e){
              e.preventDefault();
              var drawer = $(this).attr('data-drawer');

              $('.drawer:not("#'+drawer+'")').removeClass('toggled');

              if ($('#'+drawer).hasClass('toggled')) {
                  $('#'+drawer).removeClass('toggled');
              }
              else{
                  $('#'+drawer).addClass('toggled');
              }
          });

          //Close when click outside
          $(document).on('mouseup touchstart', function (e) {
              var container = $('.drawer, .tm-icon');
              if (container.has(e.target).length === 0) {
                  $('.drawer').removeClass('toggled');
                  $('.drawer-toggle').removeClass('open');
              }
          });

          //Close
          $('body').on('click touchstart', '.drawer-close', function(){
              $(this).closest('.drawer').removeClass('toggled');
              $('.drawer-toggle').removeClass('open');
          });
          wLoad();
          dLoad();
      });
    </script>-->
    </section>
<% end %>
<%= render template: "layouts/application" %>